AllCops:
  NewCops: enable
  Exclude:
    - Guardfile
    - lib/board.rb
    - lib/game.rb
    - lib/player.rb
    - lib/validator.rb
Metrics/BlockLength:
  Exclude:
    - spec/game_spec.rb
    - spec/validator_spec.rb
